---
title: "Linear Models"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


Load NYC Airbnb data.

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb %>% 
  mutate(
    stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group
  ) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighbourhood, room_type)
```

## Fit the first model

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb) 

fit # not much information

summary(fit) # gives coefficients and residuals 

fit %>% ##### model used Brox as reference group 
  broom::tidy() %>%  # gives you dataframe for outputs 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)

```


Let's change reference category.

```{r}
## makes most frequent (Manhattan) reference gorup 
fit = 
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough)
  ) %>% 
  lm(price ~ stars + borough, data = .)

fit %>% 
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)

fit %>% 
  broom::glance() %>% ## glace gives significnace 
  select(AIC)
```

## Diagnositics, looking at residuals 

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% #adds residuals to the dataframe 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point()


nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = borough, y = resid)) + 
  geom_violin() + 
  ylim(-250, 250)
```

## Hypothesis testing

one coefficient (let's say `stars`).

```{r}
fit %>% 
  broom::tidy()

#comparing models, if borough is necessary 
fit_null = lm(price ~ stars, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```


## Room type by borough

Interactions ...?

```{r}
fit = 
  nyc_airbnb %>% 
  lm(price ~ stars + borough * room_type, data = .)


fit %>% 
  broom::tidy()
```


So ... can we fit models by borough ...?
This does not "test", just exploratory analysis of effective room type 

```{r}
nyc_airbnb %>% 
  nest(df = -borough) %>% #nests everything by borough
  mutate(
    models = map(.x = df, ~lm(price ~ stars + room_type, data = .x)),   ###entire apt is referance group 
    results = map(models, broom::tidy)
  ) %>% 
  select(borough, results) %>% 
  unnest(results)
```

Quick double check ...?

```{r}
nyc_airbnb %>% 
  filter(borough == "Brooklyn") %>% 
  lm(price ~ stars + room_type, data = . ) %>% 
  broom::tidy()
```



